# Generated by Django 5.0.1 on 2024-04-27 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_rename_kind_kinds_kinds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="name",
            new_name="kind",
        ),
    ]
