# Generated by Django 5.0.1 on 2024-04-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_rename_name_products_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.IntegerField(),
        ),
    ]
