# Generated by Django 5.0.1 on 2024-05-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_products_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutCandyShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField()),
                ("shop_photo", models.ImageField(upload_to="about_candy_shop")),
                ("location", models.CharField(max_length=255)),
            ],
        ),
    ]
