# Generated by Django 5.0.1 on 2024-05-02 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_aboutcandyshop"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutCandyShop",
        ),
    ]
