# Generated by Django 5.0.1 on 2024-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_aboutcandyshop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=50)),
                ("message", models.TextField()),
            ],
        ),
    ]
