# Generated by Django 5.0.1 on 2024-05-02 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_aboutme"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutMe",
        ),
    ]
