# Generated by Django 5.0.1 on 2024-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_delete_aboutme"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("photo", models.ImageField(upload_to="about_me")),
                ("last_name", models.CharField(max_length=50)),
                ("phono_number", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
